export const STRINGS = {
  TDV_CENTERED: "table-data-value centered",
  SELECT_ITEMS: ".select-items",
  SELECT_SELECTED: ".select-selected",
  SELECT_HIDE: "select-hide",
  SELECT_ARROW_ACTIVE: "select-arrow-active",
  PICKER_SELECT: "picker-select",
  CONFIG_TABLE: "config-table",
  CONFIG_TABLE_BODY: "config-table-body",
  CONFIG_TABLE_HEADER: "config-table-header",
  CONFIG_TABLE_HEADER_CELL: "config-table-header-cell",
  CONFIG_ROW: "config-row",
  CONFIG_LABEL_CELL: "config-label-cell",
  CONFIG_INPUT_CELL: "config-input-cell",
  CONFIG_INPUT: "config-input",
  CONFIG_BUTTON_ROW: "config-button-row",
  CONFIG_BUTTON_CELL: "config-button-cell",
  CONFIG_SAVE_BUTTON: "config-save-button",
  CONFIG_RESET_BUTTON: "config-reset-button",
  CONFIG_REMOVE_BUTTON: "config-remove-button",
};
